# Generated by Django 4.2.2 on 2023-06-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=300)),
                ('summary', models.TextField(max_length=500)),
                ('school', models.CharField(max_length=300)),
                ('university', models.CharField(max_length=300)),
                ('previouswork', models.CharField(max_length=300)),
            ],
        ),
    ]
